// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

package grpc.project.pd.protos;

public interface UserIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usuarioProto.UserIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
