// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

package grpc.project.pd.protos;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usuarioProto.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.usuarioProto.Usuario user = 1;</code>
   */
  boolean hasUser();
  /**
   * <code>.usuarioProto.Usuario user = 1;</code>
   */
  grpc.project.pd.protos.Usuario getUser();
  /**
   * <code>.usuarioProto.Usuario user = 1;</code>
   */
  grpc.project.pd.protos.UsuarioOrBuilder getUserOrBuilder();
}
