// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

package grpc.project.pd.protos;

public final class usuarioProtos {
  private usuarioProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usuarioProto_Void_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usuarioProto_Void_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usuarioProto_Usuario_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usuarioProto_Usuario_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usuarioProto_UserIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usuarioProto_UserIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usuarioProto_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usuarioProto_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usuarioProto_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usuarioProto_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_usuarioProto_UserListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_usuarioProto_UserListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rusuario.proto\022\014usuarioProto\"\006\n\004Void\"D\n" +
      "\007Usuario\022\n\n\002id\030\001 \001(\005\022\014\n\004nome\030\002 \001(\t\022\r\n\005em" +
      "ail\030\003 \001(\t\022\020\n\010password\030\004 \001(\t\"\033\n\rUserIdReq" +
      "uest\022\n\n\002id\030\001 \001(\005\"2\n\013UserRequest\022#\n\004user\030" +
      "\001 \001(\0132\025.usuarioProto.Usuario\"3\n\014UserResp" +
      "onse\022#\n\004user\030\001 \001(\0132\025.usuarioProto.Usuari" +
      "o\"8\n\020UserListResponse\022$\n\005users\030\001 \003(\0132\025.u" +
      "suarioProto.Usuario2Y\n\014UsuarioProto\022I\n\014u" +
      "suarioPorId\022\033.usuarioProto.UserIdRequest" +
      "\032\032.usuarioProto.UserResponse\"\000B)\n\026grpc.p" +
      "roject.pd.protosB\rusuarioProtosP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_usuarioProto_Void_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_usuarioProto_Void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usuarioProto_Void_descriptor,
        new java.lang.String[] { });
    internal_static_usuarioProto_Usuario_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_usuarioProto_Usuario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usuarioProto_Usuario_descriptor,
        new java.lang.String[] { "Id", "Nome", "Email", "Password", });
    internal_static_usuarioProto_UserIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_usuarioProto_UserIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usuarioProto_UserIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_usuarioProto_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_usuarioProto_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usuarioProto_UserRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_usuarioProto_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_usuarioProto_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usuarioProto_UserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_usuarioProto_UserListResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_usuarioProto_UserListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_usuarioProto_UserListResponse_descriptor,
        new java.lang.String[] { "Users", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
