// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

package grpc.project.pd.protos;

public interface VoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:usuarioProto.Void)
    com.google.protobuf.MessageOrBuilder {
}
